const getPublicStaff = (staff) => ({
    id: staff._id,
    merchantId: staff.merchantId,
    bussinessId: staff.bussinessId,
    roleName: staff.roleName || "",
    firstName: staff.firstName || "",
    lastName: staff.lastName || "",
    fatherName: staff.fatherName || "",
    email: staff.email,
    cnic: staff.cnic || "",
    address: staff.address || "",
    country: staff.country || "",
    province: staff.province || "",
    district: staff.district || "",
    city: staff.city || "",
    countryCode: staff.countryCode || "",
    contactNumber: staff.contactNumber || "",
    gender: staff.gender || "",
    dateOfBirth: staff.dateOfBirth || null,
    profilePitcher: staff.profilePitcher || "",
    isActive: staff.isActive !== false,
    isEmailVerified: staff.isEmailVerified === true,
    isPasswordSet: staff.isPasswordSet === true,
    allowedSidebar: staff.allowedSidebar || [],
    accountType: "staff",
    createdBy: staff.createdBy || null,
    createdAt: staff.createdAt,
    updatedAt: staff.updatedAt,
});

export default getPublicStaff;
