const formatMerchant = (merchant) => ({
    id: merchant._id,
    bussinessId: merchant.bussinessId,
    name: merchant.name,
    slug: merchant.slug || "",
    description: merchant.description || "",
    ownerFirstName: merchant.ownerFirstName,
    ownerLastName: merchant.ownerLastName,
    ownerEmail: merchant.ownerEmail,
    ownerCnic: merchant.ownerCnic || "",
    profilePitcher: merchant.profilePitcher || "",
    frontendDomainUrl: merchant.frontendDomainUrl,
    gender: merchant.gender,
    dateOfBirth: merchant.dateOfBirth || null,
    countryCode: merchant.countryCode,
    contactNumber: merchant.contactNumber,
    secondaryContactNumber: merchant.secondaryContactNumber || "",
    headAddress: merchant.headAddress,
    country: merchant.country,
    province: merchant.province,
    city: merchant.city,
    district: merchant.district,
    postalCode: merchant.postalCode || "",
    businessType: merchant.businessType,
    isActive: merchant.isActive !== false,
    createdBy: merchant.createdBy || null,
    createdAt: merchant.createdAt,
    updatedAt: merchant.updatedAt,
});

export default formatMerchant;
