const formatBranch = (branch) => ({
    id: branch._id,
    bussinessId: branch.bussinessId,
    merchantId: branch.merchantId,
    name: branch.name,
    slug: branch.slug || "",
    branchCode: branch.branchCode,
    address: branch.address,
    country: branch.country,
    province: branch.province,
    city: branch.city,
    district: branch.district,
    postalCode: branch.postalCode || "",
    countryCode: branch.countryCode,
    contactNumber: branch.contactNumber,
    email: branch.email || "",
    managerName: branch.managerName || "",
    managerContact: branch.managerContact || "",
    openingTime: branch.openingTime || "",
    closingTime: branch.closingTime || "",
    latitude: branch.latitude || "",
    longitude: branch.longitude || "",
    isActive: branch.isActive !== false,
    createdBy: branch.createdBy || null,
    createdAt: branch.createdAt,
    updatedAt: branch.updatedAt,
});

export default formatBranch;
