const getPublicUser = (user) => ({
    id: user._id,
    firstName: user.firstName || "",
    lastName: user.lastName || "",
    email: user.email,
    bio: user.bio || "",
    designation: user.designation || "",
    country: user.country || "",
    province: user.province || "",
    city: user.city || "",
    district: user.district || "",
    address: user.address || "",
    countryCode: user.countryCode || "",
    contactNumber: user.contactNumber || "",
    gender: user.gender || "",
    dateOfBirth: user.dateOfBirth || null,
    nationalId: user.nationalId || "",
    profilePitcher: user.profilePitcher || "",
    isActive: user.isActive !== false,
    isEmailVerified: user.isEmailVerified !== false,
    isPasswordSet: user.isPasswordSet !== false,
    accountType: user.accountType || "owner",
    createdBy: user.createdBy || null,
    allowedSidebar: user.allowedSidebar || [],
    createdAt: user.createdAt,
    updatedAt: user.updatedAt,
});

export default getPublicUser;
